project:
  type: website

website:
  title: "imagination machine"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daniel-saunders-phil/
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 2



