project:
  type: website

website:
  title: "imagination machine"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 2



